-- Gamarra TV: videos en noticias + módulo de publicidad
-- Ejecutar una sola vez en Supabase > SQL Editor.

alter table public.noticias
  add column if not exists video_url text;

create table if not exists public.publicidad (
  id bigint generated by default as identity primary key,
  titulo text not null,
  imagen_url text not null,
  enlace_url text,
  descripcion text,
  activo boolean not null default true,
  orden integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists publicidad_activo_orden_idx
  on public.publicidad (activo, orden, created_at desc);

grant select on public.publicidad to anon, authenticated;
grant insert, update, delete on public.publicidad to authenticated;

grant select, insert, update, delete on public.noticias to authenticated;

-- RLS: si ya existen políticas con estos nombres, elimínalas primero.
alter table public.publicidad enable row level security;
alter table public.noticias enable row level security;

drop policy if exists "public publicidad read" on public.publicidad;
drop policy if exists "authenticated all publicidad" on public.publicidad;
drop policy if exists "authenticated all noticias" on public.noticias;

create policy "public publicidad read"
on public.publicidad
for select
using (activo = true);

create policy "authenticated all publicidad"
on public.publicidad
for all
to authenticated
using (true)
with check (true);

create policy "authenticated all noticias"
on public.noticias
for all
to authenticated
using (true)
with check (true);

-- Refrescar la caché de PostgREST.
notify pgrst, 'reload schema';
