(()=>{'use strict';
const C=window.__SUPABASE_CONFIG__||{}, sb=window.supabase?.createClient(C.url,C.publishableKey), app=document.getElementById('app');
if(!sb){app.innerHTML='<div class="error-box">No se pudo inicializar Supabase.</div>';return}
const DAYS=[['lunes','LUN',1],['martes','MAR',2],['miercoles','MIÉ',3],['jueves','JUE',4],['viernes','VIE',5],['sabado','SÁB',6],['domingo','DOM',7]];
const S={session:null,news:[],programs:[],day:null,cat:null};
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const slugify=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');
const date=v=>v?new Intl.DateTimeFormat('es-CO',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'';
const time=v=>{if(!v)return'';let [h,m]=String(v).slice(0,5).split(':').map(Number);return `${h%12||12}:${String(m).padStart(2,'0')} ${h>=12?'p.m.':'a.m.'}`};
const today=()=>{let n=new Date().getDay();return DAYS[(n+6)%7][0]};
const info=k=>DAYS.find(x=>x[0]===k)||DAYS[0];
function notify(msg,type='success'){let e=document.createElement('div');e.className='alert '+(type==='error'?'alert-error':'alert-success');e.textContent=msg;e.style.cssText='position:fixed;right:16px;bottom:16px;z-index:3000;max-width:430px;box-shadow:0 10px 30px #0003';document.body.appendChild(e);setTimeout(()=>e.remove(),4500)}
async function session(){S.session=(await sb.auth.getSession()).data.session||null;let a=document.getElementById('authLink');if(a){a.textContent=S.session?'⚙️ Panel':'🔒 Iniciar sesión';a.href=S.session?'#/admin':'#/login'}}
async function news(cat){let q=sb.from('noticias').select('id,titulo,resumen,contenido,imagen_url,categoria,publicada,created_at,slug').eq('publicada',true).order('created_at',{ascending:false}).limit(30);if(cat)q=q.eq('categoria',cat);let r=await q;if(r.error){/* compatibilidad si slug no está expuesto */let q2=sb.from('noticias').select('id,titulo,resumen,contenido,imagen_url,categoria,publicada,created_at').eq('publicada',true).order('created_at',{ascending:false}).limit(30);if(cat)q2=q2.eq('categoria',cat);r=await q2}if(r.error)throw r.error;S.news=r.data||[];return S.news}
async function programs(){let r=await sb.from('programacion').select('id,dia,dia_semana,hora_inicio,hora_fin,hora,programa,descripcion,imagen_url,activo,created_at').eq('activo',true).order('dia_semana').order('hora_inicio');if(r.error)throw r.error;S.programs=r.data||[];return S.programs}
function href(n){return '#/noticia/'+encodeURIComponent(n.slug||slugify(n.titulo)||n.id)}
function card(n){let im=n.imagen_url?`<img src="${esc(n.imagen_url)}" alt="${esc(n.titulo)}" loading="lazy">`:'<div style="height:100%;background:#123;display:grid;place-items:center;color:#fff;font-weight:900">GAMARRA TV</div>';return `<article class="news-card"><a href="${href(n)}"><div class="news-image-wrap">${im}<span class="tag">${esc(n.categoria||'Noticias')}</span></div><div class="news-body"><h3>${esc(n.titulo)}</h3><p>${esc(n.resumen||'Conozca los detalles de esta noticia en Gamarra TV.')}</p><div class="news-meta"><span>▣ ${esc(date(n.created_at))}</span><span>◷ ${Math.max(1,Math.round((n.contenido||'').length/900))} min</span></div><div class="read"><span>LEER NOTICIA</span><span class="arrow">→</span></div></div></a></article>`}
function hero(){let a=S.news[0],b=S.news[1],c=S.news[2];if(!a)return'';const box=n=>n?`<a class="feature" href="${href(n)}">${n.imagen_url?`<img src="${esc(n.imagen_url)}" alt="${esc(n.titulo)}">`:''}<div class="feature-content"><span class="tag">${esc(n.categoria||'Noticias')}</span><h2>${esc(n.titulo)}</h2></div></a>`:'';return `<section class="hero"><div class="container hero-grid"><a class="hero-main" href="${href(a)}">${a.imagen_url?`<img src="${esc(a.imagen_url)}" alt="${esc(a.titulo)}">`:''}<div class="hero-content"><span class="tag">${esc(a.categoria||'Noticias')}</span><h1>${esc(a.titulo)}</h1><p>${esc(a.resumen||'Noticias y actualidad en Gamarra TV.')}</p></div></a><div class="features">${box(b)}${box(c)}</div></div></section>`}
function live(){let d=S.day||today(),di=info(d),rows=S.programs.filter(p=>(p.dia||'').toLowerCase()===d||Number(p.dia_semana)===di[2]).sort((a,b)=>String(a.hora_inicio||a.hora).localeCompare(String(b.hora_inicio||b.hora)));let cur=new Date(),mins=cur.getHours()*60+cur.getMinutes(),nowDay=today(),current=null;const rowsHtml=rows.length?rows.map(p=>{let st=p.hora_inicio||p.hora,en=p.hora_fin||'',is=false;if(d===nowDay&&st){let [h,m]=st.slice(0,5).split(':').map(Number),sm=h*60+m,em=en?(()=>{let [x,y]=en.slice(0,5).split(':').map(Number);return x*60+y})():sm+60;is=mins>=sm&&mins<em;if(is)current=p}return `<div class="program ${is?'now':''}">${is?'<small>🔴 AHORA</small>':''}<span class="time">${esc(time(st))}${en?' - '+esc(time(en)):''}</span><strong>${esc(p.programa)}</strong>${p.descripcion?`<small>${esc(p.descripcion)}</small>`:''}</div>`}).join(''):'<div class="empty">No hay programación publicada para este día.</div>';let next=current?rows[rows.indexOf(current)+1]:rows.find(p=>{let st=p.hora_inicio||p.hora;return st&&d===nowDay&&Number(st.slice(0,2))*60+Number(st.slice(3,5))>mins});return `<section class="live-section"><div class="container"><div class="live-title"><h2>📺 Gamarra TV EN VIVO</h2><span>Señal en directo</span></div><div class="live-layout"><div><div class="player"><iframe src="${esc(C.liveUrl||'')}" title="Gamarra TV en vivo" allow="autoplay;fullscreen" allowfullscreen></iframe></div><div class="now-info"><b>🔴 ESTÁS VIENDO:</b> ${current?esc(current.programa):'Señal en vivo de Gamarra TV'} ${next?`<br><b>▶ A CONTINUACIÓN:</b> ${esc(next.programa)}`:''}</div></div><aside class="schedule"><h3>PROGRAMACIÓN</h3><div class="days">${DAYS.map(x=>`<button class="day ${d===x[0]?'active':''}" data-day="${x[0]}">${x[1]}</button>`).join('')}</div><div class="schedule-list">${rowsHtml}</div></aside></div></div></section>`}
function home(){return `${hero()}<section class="section"><div class="container"><div class="section-head"><div><span class="kicker">GTV NOTICIAS</span><h2>Últimas noticias</h2></div><div class="carousel-btns"><button id="prev">←</button><button id="next">→</button></div></div><div id="carousel" class="news-carousel">${S.news.map(card).join('')}</div></div></section>${live()}<section class="section"><div class="container"><div class="section-head"><div><span class="kicker">INFORMACIÓN</span><h2>Secciones</h2></div></div><div class="category-grid">${['Gamarra','Judicial','Deportes','Región','Nacionales','Internacionales','Entretenimiento'].map(x=>`<a class="category-box" href="#/categoria/${slugify(x)}">${x} →</a>`).join('')}</div></div></section>`}
function bindLive(){document.querySelectorAll('.day').forEach(b=>b.onclick=()=>{S.day=b.dataset.day;render()});let p=document.getElementById('prev'),n=document.getElementById('next'),c=document.getElementById('carousel');if(p)p.onclick=()=>c.scrollBy({left:-380,behavior:'smooth'});if(n)n.onclick=()=>c.scrollBy({left:380,behavior:'smooth'})}
async function article(key){let r=await sb.from('noticias').select('id,titulo,resumen,contenido,imagen_url,categoria,created_at,slug').eq('publicada',true);let rows=r.data||[];let n=rows.find(x=>String(x.slug||'')===key)||rows.find(x=>String(x.id)===key)||rows.find(x=>slugify(x.titulo)===key);if(!n){app.innerHTML='<div class="error-box"><h2>Noticia no encontrada</h2><a href="#/">Volver al inicio</a></div>';return}app.innerHTML=`<article class="article"><div class="article-inner"><span class="tag">${esc(n.categoria||'Noticias')}</span><h1>${esc(n.titulo)}</h1><div class="summary">${esc(n.resumen||'')}</div><div class="date">Publicado el ${esc(date(n.created_at))}</div>${n.imagen_url?`<img class="main-image" src="${esc(n.imagen_url)}" alt="${esc(n.titulo)}">`:''}<div class="article-content">${String(n.contenido||'').split(/\n+/).filter(Boolean).map(p=>`<p>${esc(p)}</p>`).join('')}</div></div></article>`}
function login(){app.innerHTML=`<section class="login-page"><div class="container" style="max-width:520px"><div class="panel"><h1>🔒 Iniciar sesión</h1><p>Accede al panel para publicar noticias y administrar la programación.</p><form id="loginForm"><div class="field"><label>Correo</label><input type="email" name="email" required></div><br><div class="field"><label>Contraseña</label><input type="password" name="password" required></div><br><button class="btn btn-dark">Iniciar sesión</button></form><div id="loginMsg"></div></div></div></section>`;document.getElementById('loginForm').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.currentTarget),r=await sb.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});if(r.error){document.getElementById('loginMsg').innerHTML=`<div class="alert alert-error">${esc(r.error.message)}</div>`;return}S.session=r.data.session;location.hash='#/admin';await session()}}
async function admin(){if(!S.session){location.hash='#/login';return}let ns=await sb.from('noticias').select('*').order('created_at',{ascending:false}).limit(20),ps=await sb.from('programacion').select('*').order('dia_semana').order('hora_inicio');app.innerHTML=`<section class="admin"><div class="container"><div class="panel"><div class="section-head"><div><span class="kicker">PANEL</span><h2>Administrar Gamarra TV</h2></div><button id="logout" class="btn btn-dark">Cerrar sesión</button></div><h3>📰 Publicar noticia</h3><form id="newsForm" class="form-grid"><div class="field full"><label>Título</label><input name="titulo" required></div><div class="field"><label>Categoría</label><select name="categoria"><option>gamarra</option><option>judicial</option><option>deportes</option><option>region</option><option>nacionales</option><option>internacionales</option><option>entretenimiento</option></select></div><div class="field"><label>Imagen URL</label><input name="imagen_url" type="url"></div><div class="field full"><label>Resumen</label><textarea name="resumen"></textarea></div><div class="field full"><label>Contenido</label><textarea name="contenido" required></textarea></div><div class="field"><label>Slug (opcional)</label><input name="slug" placeholder="se genera automáticamente"></div><div><br><label><input type="checkbox" name="publicada" checked> Publicar inmediatamente</label></div><div class="field full"><button class="btn btn-primary">📤 Publicar noticia</button></div></form><hr><h3>📺 Agregar programación</h3><form id="progForm" class="form-grid"><div class="field"><label>Día</label><select name="dia">${DAYS.map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('')}</select></div><div class="field"><label>Programa</label><input name="programa" required></div><div class="field"><label>Hora inicio</label><input name="hora_inicio" type="time" required></div><div class="field"><label>Hora final</label><input name="hora_fin" type="time" required></div><div class="field full"><label>Descripción</label><input name="descripcion"></div><div><label><input type="checkbox" name="activo" checked> Activo</label></div><div class="field full"><button class="btn btn-primary">📺 Guardar programa</button></div></form><div id="adminMsg"></div></div></div></section>`;document.getElementById('logout').onclick=async()=>{await sb.auth.signOut();S.session=null;location.hash='#/'};document.getElementById('newsForm').onsubmit=saveNews;document.getElementById('progForm').onsubmit=saveProg}
async function saveNews(e){e.preventDefault();if(!S.session)return;let f=new FormData(e.currentTarget),titulo=String(f.get('titulo')).trim(),slug=slugify(f.get('slug')||titulo)+'-'+Date.now().toString().slice(-6),data={titulo,resumen:f.get('resumen')||null,contenido:f.get('contenido'),imagen_url:f.get('imagen_url')||null,categoria:String(f.get('categoria')).toLowerCase(),publicada:f.get('publicada')==='on',slug};let r=await sb.from('noticias').insert(data);if(r.error){notify(r.error.message,'error');return}notify('Noticia publicada correctamente');e.currentTarget.reset();e.currentTarget.querySelector('[name=publicada]').checked=true}
async function saveProg(e){e.preventDefault();let f=new FormData(e.currentTarget),dia=String(f.get('dia')),di=info(dia),data={dia,dia_semana:di[2],hora_inicio:f.get('hora_inicio'),hora_fin:f.get('hora_fin'),hora:f.get('hora_inicio'),programa:f.get('programa'),descripcion:f.get('descripcion')||null,activo:f.get('activo')==='on'};let r=await sb.from('programacion').insert(data);if(r.error){notify(r.error.message,'error');return}notify('Programa guardado correctamente');e.currentTarget.reset();e.currentTarget.querySelector('[name=activo]').checked=true}
async function render(){let hash=location.hash||'#/';try{if(hash.startsWith('#/noticia/'))return article(decodeURIComponent(hash.slice(10)));if(hash==='#/login')return login();if(hash==='#/admin')return admin();let cat=hash.startsWith('#/categoria/')?decodeURIComponent(hash.slice(12)):null;if(hash==='#/en-vivo'||hash==='#/programacion'){await programs();app.innerHTML=live();bindLive();return}await news(cat);if(cat){app.innerHTML=`<section class="section"><div class="container"><span class="kicker">GTV NOTICIAS</span><h1>${esc(cat)}</h1><div class="news-carousel" style="grid-auto-columns:minmax(290px,1fr);grid-template-columns:repeat(3,1fr);grid-auto-flow:initial">${S.news.map(card).join('')}</div></div></section>`}else{await programs();app.innerHTML=home();bindLive()}}catch(e){console.error(e);app.innerHTML=`<div class="error-box"><h2>No se pudo cargar el contenido</h2><p>${esc(e.message||e)}</p></div>`}}
sb.auth.onAuthStateChange(()=>setTimeout(session,0));window.addEventListener('hashchange',render);(async()=>{await session();await render()})();
})();
