-- Ejecuta este SQL una sola vez en Supabase > SQL Editor.
create table if not exists public.clientes (
  id bigint generated by default as identity primary key,
  nombre text not null,
  logo_url text not null,
  web_url text not null,
  descripcion text,
  activo boolean not null default true,
  orden integer not null default 0,
  created_at timestamptz not null default now()
);

grant select on public.clientes to anon, authenticated;
grant insert, update, delete on public.clientes to authenticated;

drop policy if exists "public read clientes" on public.clientes;
drop policy if exists "authenticated all clientes" on public.clientes;
create policy "public read clientes" on public.clientes for select to anon, authenticated using (true);
create policy "authenticated all clientes" on public.clientes for all to authenticated using (true) with check (true);

insert into public.clientes (nombre, logo_url, web_url, descripcion, activo, orden)
select 'JDI El Contento','https://i.ibb.co/CphNqfMq/Chat-GPT-Image-14-sept-2026-11-0.png','https://jdielcontento.blogspot.com/','Cliente de Gamarra TV',true,1
where not exists (select 1 from public.clientes where nombre='JDI El Contento');
